## COMMON LIBRARY CONFIG
#########################################
#common:
#  application-code: 'APP'
#
#  rest-template:
#    connection-request-timeout: 30000
#    connect-timeout: 30000
#    socket-timeout: 30000
#    pooling:
#      connection-limit: 100
#      max-connection-per-route: 50
